// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attributes.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const attachAttributeToCategory = `-- name: AttachAttributeToCategory :one
INSERT INTO category_attributes (
    category_id,
    attribute_id,
    sort_order,
    is_required
) VALUES (
    $1, $2, $3, $4
)
ON CONFLICT (category_id, attribute_id) DO NOTHING
RETURNING category_id, attribute_id, sort_order, is_required, created_at, updated_at
`

type AttachAttributeToCategoryParams struct {
	CategoryID  uuid.UUID
	AttributeID uuid.UUID
	SortOrder   int32
	IsRequired  bool
}

func (q *Queries) AttachAttributeToCategory(ctx context.Context, arg AttachAttributeToCategoryParams) (CategoryAttribute, error) {
	row := q.db.QueryRowContext(ctx, attachAttributeToCategory,
		arg.CategoryID,
		arg.AttributeID,
		arg.SortOrder,
		arg.IsRequired,
	)
	var i CategoryAttribute
	err := row.Scan(
		&i.CategoryID,
		&i.AttributeID,
		&i.SortOrder,
		&i.IsRequired,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const countAttributes = `-- name: CountAttributes :one
SELECT COUNT(*) FROM attributes
WHERE deleted_at IS NULL
`

func (q *Queries) CountAttributes(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAttributes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttribute = `-- name: CreateAttribute :one
INSERT INTO attributes (
    code
) VALUES (
    $1
)
RETURNING id, code, created_at, updated_at, deleted_at
`

func (q *Queries) CreateAttribute(ctx context.Context, code string) (Attribute, error) {
	row := q.db.QueryRowContext(ctx, createAttribute, code)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createAttributeTranslation = `-- name: CreateAttributeTranslation :one
INSERT INTO attribute_translations (
    attribute_id,
    language_code,
    label,
    slug
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, attribute_id, language_code, label, slug, created_at, updated_at, deleted_at
`

type CreateAttributeTranslationParams struct {
	AttributeID  uuid.UUID
	LanguageCode LanguageCode
	Label        string
	Slug         string
}

func (q *Queries) CreateAttributeTranslation(ctx context.Context, arg CreateAttributeTranslationParams) (AttributeTranslation, error) {
	row := q.db.QueryRowContext(ctx, createAttributeTranslation,
		arg.AttributeID,
		arg.LanguageCode,
		arg.Label,
		arg.Slug,
	)
	var i AttributeTranslation
	err := row.Scan(
		&i.ID,
		&i.AttributeID,
		&i.LanguageCode,
		&i.Label,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const detachAttributeFromCategory = `-- name: DetachAttributeFromCategory :execrows
DELETE FROM category_attributes
WHERE category_id = $1
  AND attribute_id = $2
`

type DetachAttributeFromCategoryParams struct {
	CategoryID  uuid.UUID
	AttributeID uuid.UUID
}

func (q *Queries) DetachAttributeFromCategory(ctx context.Context, arg DetachAttributeFromCategoryParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, detachAttributeFromCategory, arg.CategoryID, arg.AttributeID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getAttribute = `-- name: GetAttribute :one
SELECT id, code, created_at, updated_at, deleted_at FROM attributes
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetAttribute(ctx context.Context, id uuid.UUID) (Attribute, error) {
	row := q.db.QueryRowContext(ctx, getAttribute, id)
	var i Attribute
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAttributeTranslations = `-- name: GetAttributeTranslations :many
SELECT id, attribute_id, language_code, label, slug, created_at, updated_at, deleted_at FROM attribute_translations
WHERE attribute_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetAttributeTranslations(ctx context.Context, attributeID uuid.UUID) ([]AttributeTranslation, error) {
	rows, err := q.db.QueryContext(ctx, getAttributeTranslations, attributeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AttributeTranslation
	for rows.Next() {
		var i AttributeTranslation
		if err := rows.Scan(
			&i.ID,
			&i.AttributeID,
			&i.LanguageCode,
			&i.Label,
			&i.Slug,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCategoryEffectiveAttributes = `-- name: GetCategoryEffectiveAttributes :many
WITH RECURSIVE ancestor_chain AS (
    SELECT c.id, c.parent_id, 0 AS level
    FROM categories c
    WHERE c.id = $1 AND c.deleted_at IS NULL
    UNION ALL
    SELECT c.id, c.parent_id, ac.level + 1
    FROM categories c
    JOIN ancestor_chain ac ON c.id = ac.parent_id
    WHERE c.deleted_at IS NULL
),
ranked_links AS (
    SELECT
        ca.attribute_id,
        ca.sort_order,
        ca.is_required,
        ROW_NUMBER() OVER (
            PARTITION BY ca.attribute_id
            ORDER BY ac.level ASC
        ) AS rn
    FROM ancestor_chain ac
    JOIN category_attributes ca ON ca.category_id = ac.id
)
SELECT
    a.id,
    a.code,
    rl.sort_order,
    rl.is_required,
    COALESCE(t_req.label, t_def.label) AS label,
    COALESCE(t_req.slug,  t_def.slug)  AS slug
FROM ranked_links rl
JOIN attributes a ON a.id = rl.attribute_id AND a.deleted_at IS NULL
LEFT JOIN attribute_translations t_req
    ON a.id = t_req.attribute_id
    AND t_req.language_code = $2
    AND t_req.deleted_at IS NULL
LEFT JOIN attribute_translations t_def
    ON a.id = t_def.attribute_id
    AND t_def.language_code = 'en'
    AND t_def.deleted_at IS NULL
WHERE rl.rn = 1
ORDER BY rl.sort_order, COALESCE(t_req.label, t_def.label)
`

type GetCategoryEffectiveAttributesParams struct {
	ID           uuid.UUID
	LanguageCode LanguageCode
}

type GetCategoryEffectiveAttributesRow struct {
	ID         uuid.UUID
	Code       string
	SortOrder  int32
	IsRequired bool
	Label      string
	Slug       string
}

func (q *Queries) GetCategoryEffectiveAttributes(ctx context.Context, arg GetCategoryEffectiveAttributesParams) ([]GetCategoryEffectiveAttributesRow, error) {
	rows, err := q.db.QueryContext(ctx, getCategoryEffectiveAttributes, arg.ID, arg.LanguageCode)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCategoryEffectiveAttributesRow
	for rows.Next() {
		var i GetCategoryEffectiveAttributesRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.SortOrder,
			&i.IsRequired,
			&i.Label,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttributesWithTranslation = `-- name: ListAttributesWithTranslation :many
SELECT
    a.id,
    a.code,
    a.created_at,
    a.updated_at,
    COALESCE(t_req.label, t_def.label) AS label,
    COALESCE(t_req.slug,  t_def.slug)  AS slug
FROM attributes a
LEFT JOIN attribute_translations t_req
    ON a.id = t_req.attribute_id
    AND t_req.language_code = $1
    AND t_req.deleted_at IS NULL
LEFT JOIN attribute_translations t_def
    ON a.id = t_def.attribute_id
    AND t_def.language_code = 'en'
    AND t_def.deleted_at IS NULL
WHERE a.deleted_at IS NULL
ORDER BY a.code
LIMIT $2 OFFSET $3
`

type ListAttributesWithTranslationParams struct {
	LanguageCode LanguageCode
	Limit        int32
	Offset       int32
}

type ListAttributesWithTranslationRow struct {
	ID        uuid.UUID
	Code      string
	CreatedAt time.Time
	UpdatedAt time.Time
	Label     string
	Slug      string
}

func (q *Queries) ListAttributesWithTranslation(ctx context.Context, arg ListAttributesWithTranslationParams) ([]ListAttributesWithTranslationRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttributesWithTranslation, arg.LanguageCode, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttributesWithTranslationRow
	for rows.Next() {
		var i ListAttributesWithTranslationRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Label,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
