// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createCategory = `-- name: CreateCategory :one
INSERT INTO categories (
    parent_id,
    depth,
    sort_order
) VALUES (
    $1, $2, $3
)
RETURNING id, parent_id, depth, sort_order, created_at, updated_at, deleted_at
`

type CreateCategoryParams struct {
	ParentID  uuid.NullUUID
	Depth     int32
	SortOrder int32
}

func (q *Queries) CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error) {
	row := q.db.QueryRowContext(ctx, createCategory, arg.ParentID, arg.Depth, arg.SortOrder)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Depth,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createCategoryTranslation = `-- name: CreateCategoryTranslation :one
INSERT INTO category_translations (
    category_id,
    language_code,
    title,
    slug
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, category_id, language_code, title, slug, created_at, updated_at, deleted_at
`

type CreateCategoryTranslationParams struct {
	CategoryID   uuid.UUID
	LanguageCode LanguageCode
	Title        string
	Slug         string
}

func (q *Queries) CreateCategoryTranslation(ctx context.Context, arg CreateCategoryTranslationParams) (CategoryTranslation, error) {
	row := q.db.QueryRowContext(ctx, createCategoryTranslation,
		arg.CategoryID,
		arg.LanguageCode,
		arg.Title,
		arg.Slug,
	)
	var i CategoryTranslation
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.LanguageCode,
		&i.Title,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategory = `-- name: GetCategory :one
SELECT id, parent_id, depth, sort_order, created_at, updated_at, deleted_at FROM categories
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) GetCategory(ctx context.Context, id uuid.UUID) (Category, error) {
	row := q.db.QueryRowContext(ctx, getCategory, id)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Depth,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryTranslation = `-- name: GetCategoryTranslation :one
SELECT id, category_id, language_code, title, slug, created_at, updated_at, deleted_at FROM category_translations
WHERE category_id = $1
  AND language_code = $2
  AND deleted_at IS NULL
`

type GetCategoryTranslationParams struct {
	CategoryID   uuid.UUID
	LanguageCode LanguageCode
}

func (q *Queries) GetCategoryTranslation(ctx context.Context, arg GetCategoryTranslationParams) (CategoryTranslation, error) {
	row := q.db.QueryRowContext(ctx, getCategoryTranslation, arg.CategoryID, arg.LanguageCode)
	var i CategoryTranslation
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.LanguageCode,
		&i.Title,
		&i.Slug,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getCategoryWithTranslation = `-- name: GetCategoryWithTranslation :one
SELECT 
    c.id,
    c.parent_id,
    c.depth,
    c.sort_order,
    c.created_at,
    c.updated_at,
    COALESCE(t_req.title, t_def.title) as title,
    COALESCE(t_req.slug, t_def.slug) as slug,
    COALESCE(t_req.language_code, t_def.language_code) as language_code,
    CASE 
        WHEN t_req.title IS NOT NULL THEN t_req.language_code
        ELSE t_def.language_code
    END as resolved_language
FROM categories c
LEFT JOIN category_translations t_req 
    ON c.id = t_req.category_id 
    AND t_req.language_code = $2
    AND t_req.deleted_at IS NULL
LEFT JOIN category_translations t_def 
    ON c.id = t_def.category_id 
    AND t_def.language_code = 'en'
    AND t_def.deleted_at IS NULL
WHERE c.id = $1
  AND c.deleted_at IS NULL
`

type GetCategoryWithTranslationParams struct {
	ID           uuid.UUID
	LanguageCode LanguageCode
}

type GetCategoryWithTranslationRow struct {
	ID               uuid.UUID
	ParentID         uuid.NullUUID
	Depth            int32
	SortOrder        int32
	CreatedAt        time.Time
	UpdatedAt        time.Time
	Title            string
	Slug             string
	LanguageCode     LanguageCode
	ResolvedLanguage interface{}
}

func (q *Queries) GetCategoryWithTranslation(ctx context.Context, arg GetCategoryWithTranslationParams) (GetCategoryWithTranslationRow, error) {
	row := q.db.QueryRowContext(ctx, getCategoryWithTranslation, arg.ID, arg.LanguageCode)
	var i GetCategoryWithTranslationRow
	err := row.Scan(
		&i.ID,
		&i.ParentID,
		&i.Depth,
		&i.SortOrder,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Title,
		&i.Slug,
		&i.LanguageCode,
		&i.ResolvedLanguage,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, parent_id, depth, sort_order, created_at, updated_at, deleted_at FROM categories
WHERE deleted_at IS NULL
ORDER BY depth, sort_order
LIMIT $1 OFFSET $2
`

type ListCategoriesParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListCategories(ctx context.Context, arg ListCategoriesParams) ([]Category, error) {
	rows, err := q.db.QueryContext(ctx, listCategories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Depth,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCategoriesWithTranslation = `-- name: ListCategoriesWithTranslation :many
SELECT 
    c.id,
    c.parent_id,
    c.depth,
    c.sort_order,
    c.created_at,
    c.updated_at,
    COALESCE(t_req.title, t_def.title) as title,
    COALESCE(t_req.slug, t_def.slug) as slug
FROM categories c
LEFT JOIN category_translations t_req 
    ON c.id = t_req.category_id 
    AND t_req.language_code = $1
    AND t_req.deleted_at IS NULL
LEFT JOIN category_translations t_def 
    ON c.id = t_def.category_id 
    AND t_def.language_code = 'en'
    AND t_def.deleted_at IS NULL
WHERE c.deleted_at IS NULL
ORDER BY c.depth, c.sort_order
LIMIT $2 OFFSET $3
`

type ListCategoriesWithTranslationParams struct {
	LanguageCode LanguageCode
	Limit        int32
	Offset       int32
}

type ListCategoriesWithTranslationRow struct {
	ID        uuid.UUID
	ParentID  uuid.NullUUID
	Depth     int32
	SortOrder int32
	CreatedAt time.Time
	UpdatedAt time.Time
	Title     string
	Slug      string
}

func (q *Queries) ListCategoriesWithTranslation(ctx context.Context, arg ListCategoriesWithTranslationParams) ([]ListCategoriesWithTranslationRow, error) {
	rows, err := q.db.QueryContext(ctx, listCategoriesWithTranslation, arg.LanguageCode, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesWithTranslationRow
	for rows.Next() {
		var i ListCategoriesWithTranslationRow
		if err := rows.Scan(
			&i.ID,
			&i.ParentID,
			&i.Depth,
			&i.SortOrder,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Title,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
